README.md
package-lock.json
package.json
src/Demos/Modal/Modal.js
src/Demos/Modal/__tests__/Modal.container.test.js
src/Demos/Modal/__tests__/__snapshots__/Modal.container.test.js.snap

fix(react-live): warning invalid prop anonymous

---

package-lock.json
package.json
public/environment.development.json
src/App/App.js
src/App/App.test.js
src/App/FetchProvider/FetchProvider.js
src/App/FetchProvider/FetchProvider.test.js
src/App/UserProvider/UserProvider.js
src/App/UserProvider/UserProvider.test.js
src/App/UserProvider/__snapshots__/UserProvider.test.js.snap
src/App/__snapshots__/App.test.js.snap
src/Demos/Button/__tests__/__snapshots__/Button.test.js.snap
src/Demos/Modal/__tests__/__snapshots__/Modal.container.test.js.snap
src/Demos/Modal/__tests__/__snapshots__/Modal.test.js.snap
src/Layout/Menu/Menu.container.test.js
src/Layout/Menu/Menu.test.js
src/Layout/Menu/MenuItem/MenuItem.container.test.js
src/Layout/Routes/Routes.js
src/Layout/Routes/Routes.test.js
src/Layout/Routes/__snapshots__/Routes.test.js.snap
src/shared/hoc/withUser.js
src/shared/hoc/withWrapperEnvAndAuth.js

Mise à jour de React OIDC v4 : 
https://www.npmjs.com/package/@axa-fr/react-oidc-context
Guide de migration : https://github.com/AxaGuilDEv/react-oidc/blob/master/MIGRATION_GUIDE_V3_TO_V4.md
Cette version a été complètement réécrite avec https://github.com/openid/AppAuth-JS pour remplacer oidc-client qui n'est plus maintenue.
Cette version utilise les services workers et un mode dégradé avec le même fonctionnement qu'avant.
Dans cette PR je reste pour le moment en mode dégradé.

chore(deps): react-oidc v4

---

package-lock.json
package.json
src/Members/__tests__/Members.feature
src/Members/__tests__/Members.spec.js
src/shared/components/index.js

fix(eslint): fix some errors and warnings

---

.github/workflows/build.yml

update node to v16 for github action workflow build

ci(node): update node to v16

---

.husky/commit-msg
.husky/pre-commit
README.md
package-lock.json
package.json

chore(husky): update v4 to v7

---

package-lock.json
package.json

chore(apex-chart react-oidc): update packages

chore(apex-chart react-oidc): update packages

---

public/environment.development.json
public/environment.production.json
public/environment.production.local.json

feat(openid): change demo url openid server

feat(openid): change demo url openid server

---

src/Layout/Menu/__tests__/Menu.container.test.js
src/SearchMembers/DownloadLink/__tests__/DownloadLink.test.js
src/SearchMembers/SearchForm/__tests__/SearchForm.container.test.js
src/SearchMembers/SearchForm/__tests__/SearchForm.test.js
src/shared/components/Loader/__tests__/Loader.container.test.js
src/shared/components/Table/Body/Line/Td/__tests__/Td.container.test.js
src/shared/components/Table/Body/Line/Td/__tests__/Td.test.js
src/shared/components/Table/Body/Line/__tests__/Line.container.test.js
src/shared/components/Table/Body/Line/__tests__/Line.test.js
src/shared/components/Table/Body/__tests__/Body.test.js
src/shared/components/Table/Header/Th/ThSortable/__tests__/ThSortable.test.js
src/shared/components/Table/Header/Th/__tests__/Th.container.test.js
src/shared/components/Table/Header/Th/__tests__/Th.test.js
src/shared/components/Table/Header/__tests__/Header.test.js
src/shared/components/Table/__tests__/Table.container.test.js
src/shared/components/Table/__tests__/Table.test.js

refactor(rtl): jest dom

---

package.json
public/environment.development.json
public/environment.production.json
public/environment.production.local.json
src/shared/testsUtils/constants.js
src/shared/testsUtils/customRender.js
src/shared/testsUtils/index.js
src/shared/testsUtils/mocks/handlers.js

change to the new mock api deployed on vercel
This version allow to serve static file with vercel

feat(apiurl): change to vercel version

---

src/App/__tests__/__snapshots__/App.test.js.snap
src/pages/SlashDesignSystem/__tests__/__snapshots__/SlashDesignSystem.test.js.snap
src/shared/components/Cards/Card/__tests__/__snapshots__/Card.test.js.snap
src/shared/components/Cards/__tests__/__snapshots__/Cards.test.js.snap
src/shared/constants.js

fix(url): design system

---

package.json

fix(build): homepage param package.json

---

src/App/NotificationProvider/Notifications/Notifications.scss
src/Layout/Menu/Menu.scss
src/Layout/Menu/Menu.tsx
src/Layout/Menu/MenuItem/MenuItem.container.tsx
src/Layout/Menu/MenuItem/MenuItem.d.ts
src/Layout/Menu/MenuItem/MenuItem.tsx
src/Layout/TitleBar/TitleBar.scss
src/shared/components/LiveCode/livecode.scss

fix(design): better responsive

---

src/shared/helpers/validation.generic.test.ts

refactor(setstate): duplicate functions

---

src/pages/Demos/Members/Members.hook.ts
src/pages/Demos/SearchMembers/__tests/SearchMembers.container.test.tsx
src/shared/components/Table/formatDataTable.ts

fix(sonar): codesmells

---

src/App/EnvironmentProvider/Environment.tsx
src/App/EnvironmentProvider/__tests__/Environment.test.tsx
src/App/EnvironmentProvider/index.ts

change load method for environment because we have to load these data in asynchone

fix(environment): change load method environment

---

README.md
package.json
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/Layout/Menu/Menu.scss
src/Layout/TitleBar/TitleBar.scss
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap
src/shared/components/Editor/CodeEditor/CodeEditor.scss
src/shared/components/Editor/CodeEditor/Templates/Templates.tsx
src/shared/components/Editor/CodeEditor/Templates/__tests__/__snapshots__/Templates.test.tsx.snap
src/shared/components/Editor/Editor.scss
src/shared/components/Loader/Loader.scss
src/shared/scss/custom.scss
src/shared/scss/variables.scss

fix(layout): responsive anomalies

---

package-lock.json
package.json
src/App/Routes/Routes.tsx
src/App/Routes/constants.ts
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
src/Layout/Menu/constants.ts
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/Tabs/Tabs.tsx
src/pages/Demos/Tabs/__tests__/Tabs.test.tsx
src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
src/pages/Demos/Tabs/constants.ts
src/pages/Demos/Tabs/index.ts
src/pages/Demos/Tabs/knobs.json
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap

feat(tabs): add playground

---

src/App/Routes/Routes.tsx
src/App/Routes/constants.ts
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
src/Layout/Menu/constants.ts
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/SelectInput/SelectInput.tsx
src/pages/Demos/SelectInput/__tests__/SelectInput.test.tsx
src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
src/pages/Demos/SelectInput/constants.ts
src/pages/Demos/SelectInput/index.ts
src/pages/Demos/SelectInput/knobs.json
src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap

feat(SelectInput): add playground

---

src/App/Routes/Routes.tsx
src/App/Routes/constants.ts
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
src/Layout/Menu/constants.ts
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Badge/Badge.tsx
src/pages/Demos/Badge/__tests__/Badge.test.tsx
src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
src/pages/Demos/Badge/constants.ts
src/pages/Demos/Badge/index.ts
src/pages/Demos/Badge/knobs.json
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap

feat(badge): add playground

---

package.json
scripts/.gitignore
scripts/clean.js
scripts/package.json
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Footer/__tests__/__snapshots__/Footer.test.tsx.snap
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
src/pages/Demos/TextInput/TextInput.tsx
src/pages/Demos/TextInput/__tests__/TextInput.test.tsx
src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap
src/shared/components/Editor/Editor.scss
src/shared/components/Editor/Editor.tsx
src/shared/components/Editor/__tests__/Editor.test.tsx
src/shared/components/LiveCode/ClipBoard/ClipBoard.scss
src/shared/components/LiveCode/LiveCode.tsx
src/shared/components/LiveCode/Livecode.scss

Fix render value with autofocus

fix(textinput): render when change value

---

src/App/Routes/Routes.tsx
src/App/Routes/constants.ts
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
src/Layout/Menu/constants.ts
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Help/Help.tsx
src/pages/Demos/Help/__tests__/Help.test.tsx
src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
src/pages/Demos/Help/constants.ts
src/pages/Demos/Help/index.ts
src/pages/Demos/Help/knobs.json
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
src/pages/Demos/Tabs/__tests__/__snapshots__/Tabs.test.tsx.snap
src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
src/pages/Demos/Title/Title.tsx
src/pages/Demos/Title/__tests__/Title.test.tsx
src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
src/pages/Demos/Title/constants.ts
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap

feat(help): add playground help

---

src/App/Routes/Routes.tsx
src/App/Routes/constants.ts
src/App/__tests__/__snapshots__/App.test.tsx.snap
src/Layout/Menu/__tests__/__snapshots__/Menu.test.tsx.snap
src/Layout/Menu/constants.ts
src/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Alert/__tests__/__snapshots__/Alert.test.tsx.snap
src/pages/Demos/Badge/__tests__/__snapshots__/Badge.test.tsx.snap
src/pages/Demos/Button/__tests__/__snapshots__/Button.test.tsx.snap
src/pages/Demos/Header/Header.scss
src/pages/Demos/Header/Header.tsx
src/pages/Demos/Header/__tests__/Header.test.tsx
src/pages/Demos/Header/__tests__/__snapshots__/Header.test.tsx.snap
src/pages/Demos/Header/constants.ts
src/pages/Demos/Header/index.ts
src/pages/Demos/Header/knobs.json
src/pages/Demos/Help/__tests__/__snapshots__/Help.test.tsx.snap
src/pages/Demos/Layout/__tests__/__snapshots__/Layout.test.tsx.snap
src/pages/Demos/Members/__tests__/__snapshots__/Members.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.container.test.tsx.snap
src/pages/Demos/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
src/pages/Demos/Notification/__tests__/__snapshots__/Notification.test.tsx.snap
src/pages/Demos/RadioInput/__tests__/__snapshots__/RadioInput.test.tsx.snap
src/pages/Demos/Restitution/__tests__/__snapshots__/Restitution.test.tsx.snap
src/pages/Demos/SearchMembers/__tests/__snapshots__/SearchMembers.test.tsx.snap
src/pages/Demos/SelectInput/__tests__/__snapshots__/SelectInput.test.tsx.snap
src/pages/Demos/TextInput/__tests__/__snapshots__/TextInput.test.tsx.snap
src/pages/Demos/Title/__tests__/__snapshots__/Title.test.tsx.snap
src/pages/Home/__tests__/__snapshots__/Home.test.tsx.snap

feat(header): add playground header

---

src/pages/Demos/SearchMembers/SearchForm/SearchForm.tsx

fix(searchform): fix forwardRef in search form

---

package.json
src/pages/Demos/DateInput/__tests__/DateInput.test.tsx
src/pages/Demos/DateInput/__tests__/__snapshots__/DateInput.test.tsx.snap
src/shared/components/Editor/InputEditor/__tests__/__snapshots__/InputEditor.test.tsx.snap

fix self deleted script for windows

fix(clean): self deleted script for windows

---

scripts/files/public/environment.development.json

Fix environment apiUrl from scripts folder when the project is cleaned

fix(environment): fix environment apiUrl from scritps

---

src/Layout/Footer/Footer.scss
src/Layout/Header/Header.scss
src/Layout/Layout.scss
src/Layout/Layout.tsx
src/Layout/TitleBar/TitleBar.scss
src/pages/Demos/DateInput/DateInput.tsx
src/shared/components/LiveCode/Livecode.scss
src/shared/components/Table/constants.ts
src/shared/hoc/WithClassNameModifier.tsx
src/shared/scss/custom.scss

feat(style): fixes styles
